[package]
name = "binance-types"
version = "0.1.0"
edition = "2021"

[features]
strict-enums = []

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_repr = "0.1"
strum = "0.24.0"
strum_macros = "0.24.0"

[dev-dependencies]
serde_json = "1.0"
